# Generated by Django 4.1.7 on 2023-07-20 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectiveSubject",
            fields=[
                ("elecsub_id", models.AutoField(primary_key=True, serialize=False)),
                ("elecsub_name", models.CharField(max_length=40)),
                ("elecsub_credit", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GraduationCondition",
            fields=[
                ("grdcon_id", models.AutoField(primary_key=True, serialize=False)),
                ("grdcon_stunum", models.IntegerField()),
                ("grdcon_total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("maj_id", models.AutoField(primary_key=True, serialize=False)),
                ("maj_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="MajorSubject",
            fields=[
                ("majsub_id", models.AutoField(primary_key=True, serialize=False)),
                ("majsub_grade", models.PositiveIntegerField()),
                ("majsub_semester", models.CharField(max_length=2)),
                ("majsub_name", models.CharField(max_length=40)),
                ("majsub_credit", models.PositiveIntegerField()),
                ("majsub_required", models.BooleanField(default=False)),
                (
                    "major",
                    models.ForeignKey(
                        db_column="maj_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.major",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("stu_id", models.AutoField(primary_key=True, serialize=False)),
                ("stu_password", models.CharField(max_length=50)),
                ("stu_name", models.CharField(max_length=10)),
                ("stu_number", models.CharField(max_length=2)),
                ("stu_email", models.EmailField(max_length=254)),
                ("stu_secondmajor", models.CharField(max_length=5)),
                (
                    "stu_majorcredit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "stu_secondmajorcredit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "stu_electivecredit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "stu_retakecredit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "firstmajor",
                    models.ForeignKey(
                        db_column="maj_id1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firstmajor",
                        to="planner.major",
                    ),
                ),
                (
                    "graduatecondition",
                    models.ForeignKey(
                        db_column="grdcon_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.graduationcondition",
                    ),
                ),
                (
                    "secondmajor",
                    models.ForeignKey(
                        db_column="maj_id2",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondmajor",
                        to="planner.major",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("time_id", models.AutoField(primary_key=True, serialize=False)),
                ("time_semester", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        db_column="stu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimetableDetail",
            fields=[
                ("timedetail_id", models.AutoField(primary_key=True, serialize=False)),
                ("timedetail_retake", models.BooleanField(default=False)),
                (
                    "majorsubjet",
                    models.ForeignKey(
                        db_column="majsub_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.majorsubject",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        db_column="time_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraudationConditionDetail",
            fields=[
                ("grddet_id", models.AutoField(primary_key=True, serialize=False)),
                ("grddet_name", models.CharField(max_length=10)),
                ("grddet_majormintotal", models.PositiveIntegerField()),
                ("grddet_secondmajormintotal", models.PositiveIntegerField()),
                ("grddet_minormintotal", models.PositiveIntegerField()),
                ("grddet_electivemintotal", models.PositiveIntegerField()),
                (
                    "major",
                    models.ForeignKey(
                        db_column="maj_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.major",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="graduationcondition",
            name="grdconditiondetail",
            field=models.ForeignKey(
                db_column="grddet_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="planner.graudationconditiondetail",
            ),
        ),
    ]
